# Global timing constants
timing_constants:
  birthday_email_days_before: 14
  effective_date_days_before: 30
  pre_window_exclusion_days: 60

# AEP configuration
aep_config:
  default_dates:
    - month: 8
      day: 18
    - month: 8
      day: 25
    - month: 9
      day: 1
    - month: 9
      day: 7
  years: [2023, 2024, 2025, 2026, 2027]

# State-specific rules
state_rules:
  CA:
    type: "birthday"
    window_before: 30
    window_after: 30
  ID:
    type: "birthday"
    window_before: 0
    window_after: 63
  IL:
    type: "birthday"
    window_before: 0
    window_after: 45
    special_rules:
      age_limit: 76
  KY:
    type: "birthday"
    window_before: 0
    window_after: 60
  LA:
    type: "birthday"
    window_before: 30
    window_after: 63
  MD:
    type: "birthday"
    window_before: 0
    window_after: 31
  NV:
    type: "birthday"
    window_before: 0
    window_after: 60
    special_rules:
      use_month_start: true
  OK:
    type: "birthday"
    window_before: 0
    window_after: 60
  OR:
    type: "birthday"
    window_before: 0
    window_after: 31
  MO:
    type: "effective_date"
    window_before: 30
    window_after: 33
  CT:
    type: "year_round"
  MA:
    type: "year_round"
  NY:
    type: "year_round"
  WA:
    type: "year_round"

# Contact-specific rules              